subjects:
- sub-NSD103
- sub-NSD104
- sub-NSD105
- sub-NSD106
# - sub-NSD107
- sub-NSD108
- sub-NSD109
- sub-NSD110
- sub-NSD111
- sub-NSD112
- sub-NSD113
- sub-NSD114
- sub-NSD115
- sub-NSD116
- sub-NSD117
- sub-NSD119
- sub-NSD120
- sub-NSD122
- sub-NSD123
- sub-NSD124
- sub-NSD125
- sub-NSD126
- sub-NSD127
- sub-NSD128
- sub-NSD129
- sub-NSD130
- sub-NSD132
- sub-NSD133
- sub-NSD134
- sub-NSD135
- sub-NSD136
- sub-NSD138
- sub-NSD140
- sub-NSD142
- sub-NSD145
- sub-NSD146
- sub-NSD147
- sub-NSD148
- sub-NSD149
- sub-NSD150
- sub-NSD151
- sub-NSD153
- sub-NSD155
movies:
  - iteration
  - defeat
  - growth
  - lemonade
data_path: '/data/mbonner5/chan21/datasets/finn_final/trimmed/derivatives'
roi_names:
- occipital
- ventral
- temporal
- semantic
metric: 'cov'
alignment: 'functional'
random_state: 0
perform_permutations: false
n_permutations: 1000
perform_downsampling: false
block_size: 6
n_downsample: 0
overwrite: True
